(deftheme gruvbox
  "Created 2014-08-06.")

(custom-theme-set-variables
 'gruvbox
 '(ansi-color-names-vector ["#3c3836" "#fb4934" "#b8bb26" "#fabd2f" "#83a598" "#d3869b" "#8ec07c" "#ebdbb2"])
 '(powerline-color0 "#3c3836")
 '(powerline-color1 "#3C3C3C")
 '(powerline-color2 "#515151"))

(custom-theme-set-faces
 'gruvbox
 '(cursor ((t (:background "#fdf4c1"))))
 '(mode-line ((t (:box nil :background "#fabd2f" :foreground "#282828"))))
 '(mode-line-inactive ((t (:box nil :background "#504945" :foreground "#a89984"))))
 '(fringe ((t (:background "#282828"))))
 '(linum ((t (:foreground "#7c6f64"))))
 '(hl-line ((t (:background "#3c3836"))))
 '(region ((t (:background "#504945"))))
 '(minibuffer-prompt ((t (:background "#282828" :foreground "#b8bb26" :bold t))))
 '(font-lock-builtin-face ((t (:foreground "#fe8019"))))
 '(font-lock-constant-face ((t (:foreground "#d3869b"))))
 '(font-lock-comment-face ((t (:foreground "#7c6f64"))))
 '(font-lock-function-name-face ((t (:foreground "#b8bb26"))))
 '(font-lock-keyword-face ((t (:foreground "#fb4934"))))
 '(font-lock-string-face ((t (:foreground "#b8bb26"))))
 '(font-lock-variable-name-face ((t (:foreground "#83a598"))))
 '(font-lock-type-face ((t (:foreground "#d3869b"))))
 '(font-lock-warning-face ((t (:foreground "#fb4934" :bold t))))
 '(whitespace-space ((t (:background "#282828" :foreground "#7c6f64"))))
 '(whitespace-hspace ((t (:background "#282828" :foreground "#7c6f64"))))
 '(whitespace-tab ((t (:background "#282828" :foreground "#7c6f64"))))
 '(whitespace-newline ((t (:background "#282828" :foreground "#7c6f64"))))
 '(whitespace-trailing ((t (:background "#3c3836" :foreground "#fb4934"))))
 '(whitespace-line ((t (:background "#3c3836" :foreground "#fb4934"))))
 '(whitespace-space-before-tab ((t (:background "#282828" :foreground "#7c6f64"))))
 '(whitespace-indentation ((t (:background "#282828" :foreground "#7c6f64"))))
 '(whitespace-empty ((t (:background nil :foreground nil))))
 '(whitespace-space-after-tab ((t (:background "#282828" :foreground "#7c6f64"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#458588"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#b16286"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#cc241d"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#d65d0e"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#458488"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#b16286"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#cc241d"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#d65d0e"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#458588"))))
 '(rainbow-delimiters-depth-10-face ((t (:foreground "#b16286"))))
 '(rainbow-delimiters-depth-11-face ((t (:foreground "#cc241d"))))
 '(rainbow-delimiters-depth-12-face ((t (:foreground "#d65d0e"))))
 '(rainbow-delimiters-unmatched-face ((t (:background nil :foreground "#fdf4c1"))))
 '(linum-relative-current-face ((t (:background "#3c3836" :foreground "#a89984"))))
 '(sp-pair-overlay-face ((t (:background "#504945"))))
 '(sp-show-pair-match-face ((t (:background "#504945"))))
 '(sp-show-pair-mismatch-face ((t (:background "#fb4934"))))
 '(elscreen-tab-background-face ((t (:box nil :background "#282828"))))
 '(elscreen-tab-control-face ((t (:box nil :background "#504945" :foreground "#fb4934" :underline nil))))
 '(elscreen-tab-current-screen-face ((t (:box nil :background "#7c6f64" :foreground "#282828"))))
 '(elscreen-tab-other-screen-face ((t (:box nil :background "#504945" :foreground "#a89984" :underline nil))))
 '(ag-hit-face ((t (:foreground "#83a598"))))
 '(ag-match-face ((t (:foreground "#fb4934"))))
 '(diff-changed ((t (:background nil :foreground "#ebdbb2"))))
 '(diff-added ((t (:background nil :foreground "#b8bb26"))))
 '(diff-removed ((t (:background nil :foreground "#fb4934"))))
 '(diff-indicator-changed ((t (:inherit diff-changed))))
 '(diff-indicator-added ((t (:inherit diff-added))))
 '(diff-indicator-removed ((t (:inherit diff-removed))))
 '(term-color-black ((t (:foreground "#3c3836"))))
 '(term-color-blue ((t (:foreground "#83a598"))))
 '(term-color-cyan ((t (:foreground "#8ec07c"))))
 '(term-color-green ((t (:foreground "#b8bb26"))))
 '(term-color-magenta ((t (:foreground "#d3869b"))))
 '(term-color-red ((t (:foreground "#fb4934"))))
 '(term-color-white ((t (:foreground "#ebdbb2"))))
 '(term-color-yellow ((t (:foreground "#fabd2f"))))
 '(term-default-fg-color ((t (:foreground "#fdf4c1"))))
 '(term-default-bg-color ((t (:background "#282828"))))
 '(highlight-current-line-face ((t (:background "#323232"))))
 '(default ((t (:background "#282828" :foreground "#fdf4c1")))))

(provide-theme 'gruvbox)
